--------------------------------------------------------
--  파일이 생성됨 - 금요일-3월-18-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ARTIST
--------------------------------------------------------

  CREATE TABLE "ATEAM"."ARTIST" 
   (	"NAME" VARCHAR2(1500 BYTE), 
	"IMG" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SUGGEST_MSG
--------------------------------------------------------

  CREATE TABLE "ATEAM"."SUGGEST_MSG" 
   (	"SONG_ID" NUMBER, 
	"FROM_USER" VARCHAR2(40 BYTE), 
	"TO_USER" VARCHAR2(40 BYTE), 
	"IS_TAKEN" CHAR(1 BYTE), 
	"ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USER_COMMENT
--------------------------------------------------------

  CREATE TABLE "ATEAM"."USER_COMMENT" 
   (	"SONG_ID" NUMBER, 
	"MEM_ACC_ID" VARCHAR2(50 BYTE), 
	"MY_CONTENT" VARCHAR2(600 BYTE), 
	"WRITE_TIME" DATE DEFAULT sysdate, 
	"ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SONG_RECORD
--------------------------------------------------------

  CREATE TABLE "ATEAM"."SONG_RECORD" 
   (	"SONG_ID" NUMBER, 
	"MEM_ACC_ID" VARCHAR2(40 BYTE), 
	"RECORD_TIME" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SONG
--------------------------------------------------------

  CREATE TABLE "ATEAM"."SONG" 
   (	"SONG_ID" NUMBER, 
	"SONG_TITLE" VARCHAR2(1500 BYTE), 
	"SONG_ALBUM" VARCHAR2(1500 BYTE), 
	"SONG_ARTIST" VARCHAR2(1500 BYTE), 
	"SONG_IMG" VARCHAR2(3300 BYTE), 
	"SONG_GENRE" VARCHAR2(1500 BYTE), 
	"SONG_YOUTUBE_LINK" VARCHAR2(3000 BYTE), 
	"SONG_LYRICS" LONG, 
	"SONG_THEMA" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RECOMMENDED_PLAYLIST
--------------------------------------------------------

  CREATE TABLE "ATEAM"."RECOMMENDED_PLAYLIST" 
   (	"ID" NUMBER, 
	"SONG_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RECOMMENDED_INFO
--------------------------------------------------------

  CREATE TABLE "ATEAM"."RECOMMENDED_INFO" 
   (	"ID" NUMBER, 
	"TITLE" VARCHAR2(60 BYTE), 
	"CONTENT" VARCHAR2(120 BYTE), 
	"USER_ID" VARCHAR2(40 BYTE), 
	"WRITTEN_TIME" DATE DEFAULT sysdate, 
	"THUMBS_UP" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RECOMMEND_THEMA
--------------------------------------------------------

  CREATE TABLE "ATEAM"."RECOMMEND_THEMA" 
   (	"THEMA_COMMENT" VARCHAR2(1200 BYTE), 
	"THEMA_CODE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MEM
--------------------------------------------------------

  CREATE TABLE "ATEAM"."MEM" 
   (	"MEM_ACC_ID" VARCHAR2(40 BYTE), 
	"MEM_PWD" VARCHAR2(50 BYTE), 
	"MEM_NICK" VARCHAR2(100 BYTE), 
	"MEM_EMAIL" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LIKE_RECOMMEND_LIST
--------------------------------------------------------

  CREATE TABLE "ATEAM"."LIKE_RECOMMEND_LIST" 
   (	"MEM_ACC_ID" VARCHAR2(40 BYTE), 
	"ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LIKE_IT_LIST
--------------------------------------------------------

  CREATE TABLE "ATEAM"."LIKE_IT_LIST" 
   (	"MEM_ACC_ID" VARCHAR2(40 BYTE), 
	"SONG_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LIKE_ARTIST_LIST
--------------------------------------------------------

  CREATE TABLE "ATEAM"."LIKE_ARTIST_LIST" 
   (	"USER_ID" VARCHAR2(40 BYTE), 
	"ARTIST" VARCHAR2(1500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FRIEND_WAIT
--------------------------------------------------------

  CREATE TABLE "ATEAM"."FRIEND_WAIT" 
   (	"USERID" VARCHAR2(40 BYTE), 
	"FRIENDID" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FRIEND
--------------------------------------------------------

  CREATE TABLE "ATEAM"."FRIEND" 
   (	"USERID" VARCHAR2(40 BYTE), 
	"FRIENDID" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007117
--------------------------------------------------------

  CREATE UNIQUE INDEX "ATEAM"."SYS_C007117" ON "ATEAM"."ARTIST" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SUGGEST_MSG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ATEAM"."SUGGEST_MSG_PK" ON "ATEAM"."SUGGEST_MSG" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index USER_COMMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ATEAM"."USER_COMMENT_PK" ON "ATEAM"."USER_COMMENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007031
--------------------------------------------------------

  CREATE UNIQUE INDEX "ATEAM"."SYS_C007031" ON "ATEAM"."SONG" ("SONG_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RECOMMENDED_INFO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ATEAM"."RECOMMENDED_INFO_PK" ON "ATEAM"."RECOMMENDED_INFO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MEM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ATEAM"."MEM_PK" ON "ATEAM"."MEM" ("MEM_ACC_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger SUGGEST_MSG_PK
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ATEAM"."SUGGEST_MSG_PK" 
   before insert on "ATEAM"."SUGGEST_MSG" 
   for each row 
begin  
   if inserting then 
      if :NEW."ID" is null then 
         select SUGGEST_MSG_SEQ.nextval into :NEW."ID" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "ATEAM"."SUGGEST_MSG_PK" ENABLE;
--------------------------------------------------------
--  DDL for Trigger USER_COMMENT_INS
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ATEAM"."USER_COMMENT_INS" 
  before insert on USER_COMMENT
  for each row
   WHEN (new.ID is null) begin
  select user_comment_seq.nextval into :new.id from dual;
end user_comment_ins;
/
ALTER TRIGGER "ATEAM"."USER_COMMENT_INS" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SONG_INS
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ATEAM"."SONG_INS" 
  before insert on song
  for each row
   WHEN (new.Song_ID is null) begin
  select SONG_SEQ.nextval into :new.Song_ID from dual;
end song_ins;
/
ALTER TRIGGER "ATEAM"."SONG_INS" ENABLE;
--------------------------------------------------------
--  DDL for Trigger RECOMMENDED_INS
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ATEAM"."RECOMMENDED_INS" 
  before insert on RECOMMENDED_INFO
  for each row
   WHEN (new.ID is null) begin
  select RECOMMENDED_INFO_seq.nextval into :new.id from dual;
end recommended_ins;
/
ALTER TRIGGER "ATEAM"."RECOMMENDED_INS" ENABLE;
--------------------------------------------------------
--  Constraints for Table ARTIST
--------------------------------------------------------

  ALTER TABLE "ATEAM"."ARTIST" ADD PRIMARY KEY ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SUGGEST_MSG
--------------------------------------------------------

  ALTER TABLE "ATEAM"."SUGGEST_MSG" ADD CONSTRAINT "SUGGEST_MSG_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USER_COMMENT
--------------------------------------------------------

  ALTER TABLE "ATEAM"."USER_COMMENT" ADD CONSTRAINT "USER_COMMENT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ATEAM"."USER_COMMENT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SONG
--------------------------------------------------------

  ALTER TABLE "ATEAM"."SONG" ADD PRIMARY KEY ("SONG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RECOMMENDED_INFO
--------------------------------------------------------

  ALTER TABLE "ATEAM"."RECOMMENDED_INFO" ADD CONSTRAINT "RECOMMENDED_INFO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ATEAM"."RECOMMENDED_INFO" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEM
--------------------------------------------------------

  ALTER TABLE "ATEAM"."MEM" ADD CONSTRAINT "MEM_PK" PRIMARY KEY ("MEM_ACC_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ATEAM"."MEM" MODIFY ("MEM_ACC_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table SUGGEST_MSG
--------------------------------------------------------

  ALTER TABLE "ATEAM"."SUGGEST_MSG" ADD CONSTRAINT "SUGGEST_FROM_FK" FOREIGN KEY ("FROM_USER")
	  REFERENCES "ATEAM"."MEM" ("MEM_ACC_ID") ENABLE;
  ALTER TABLE "ATEAM"."SUGGEST_MSG" ADD CONSTRAINT "SUGGEST_MSG_SONG_FK" FOREIGN KEY ("SONG_ID")
	  REFERENCES "ATEAM"."SONG" ("SONG_ID") ENABLE;
  ALTER TABLE "ATEAM"."SUGGEST_MSG" ADD CONSTRAINT "SUGGEST_TO_FK" FOREIGN KEY ("TO_USER")
	  REFERENCES "ATEAM"."MEM" ("MEM_ACC_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USER_COMMENT
--------------------------------------------------------

  ALTER TABLE "ATEAM"."USER_COMMENT" ADD CONSTRAINT "COMMENT_USER_FK" FOREIGN KEY ("MEM_ACC_ID")
	  REFERENCES "ATEAM"."MEM" ("MEM_ACC_ID") ENABLE;
  ALTER TABLE "ATEAM"."USER_COMMENT" ADD CONSTRAINT "USER_COMMENT_SONG_FK" FOREIGN KEY ("SONG_ID")
	  REFERENCES "ATEAM"."SONG" ("SONG_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RECOMMENDED_PLAYLIST
--------------------------------------------------------

  ALTER TABLE "ATEAM"."RECOMMENDED_PLAYLIST" ADD CONSTRAINT "RECOMMENDED_SONG_FK" FOREIGN KEY ("SONG_ID")
	  REFERENCES "ATEAM"."SONG" ("SONG_ID") ENABLE;
  ALTER TABLE "ATEAM"."RECOMMENDED_PLAYLIST" ADD CONSTRAINT "RECOMMEND_PLAYLIST_FK" FOREIGN KEY ("ID")
	  REFERENCES "ATEAM"."RECOMMENDED_INFO" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RECOMMENDED_INFO
--------------------------------------------------------

  ALTER TABLE "ATEAM"."RECOMMENDED_INFO" ADD CONSTRAINT "RECOMMEND_USER_FK" FOREIGN KEY ("USER_ID")
	  REFERENCES "ATEAM"."MEM" ("MEM_ACC_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LIKE_RECOMMEND_LIST
--------------------------------------------------------

  ALTER TABLE "ATEAM"."LIKE_RECOMMEND_LIST" ADD CONSTRAINT "LIKE_RECOMMEND_FK" FOREIGN KEY ("ID")
	  REFERENCES "ATEAM"."RECOMMENDED_INFO" ("ID") ENABLE;
  ALTER TABLE "ATEAM"."LIKE_RECOMMEND_LIST" ADD CONSTRAINT "LIKE_RECOMMEND_USER_FK" FOREIGN KEY ("MEM_ACC_ID")
	  REFERENCES "ATEAM"."MEM" ("MEM_ACC_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LIKE_IT_LIST
--------------------------------------------------------

  ALTER TABLE "ATEAM"."LIKE_IT_LIST" ADD CONSTRAINT "LIKE_IT_SONG_FK" FOREIGN KEY ("SONG_ID")
	  REFERENCES "ATEAM"."SONG" ("SONG_ID") ENABLE;
  ALTER TABLE "ATEAM"."LIKE_IT_LIST" ADD CONSTRAINT "LIKE_IT_USER_FK" FOREIGN KEY ("MEM_ACC_ID")
	  REFERENCES "ATEAM"."MEM" ("MEM_ACC_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LIKE_ARTIST_LIST
--------------------------------------------------------

  ALTER TABLE "ATEAM"."LIKE_ARTIST_LIST" ADD CONSTRAINT "LIKE_ARTIST_FK" FOREIGN KEY ("ARTIST")
	  REFERENCES "ATEAM"."ARTIST" ("NAME") ENABLE;
  ALTER TABLE "ATEAM"."LIKE_ARTIST_LIST" ADD CONSTRAINT "LIKE_ARTIST_USER_FK" FOREIGN KEY ("USER_ID")
	  REFERENCES "ATEAM"."MEM" ("MEM_ACC_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FRIEND_WAIT
--------------------------------------------------------

  ALTER TABLE "ATEAM"."FRIEND_WAIT" ADD CONSTRAINT "FRIEND_WAIT_FK" FOREIGN KEY ("FRIENDID")
	  REFERENCES "ATEAM"."MEM" ("MEM_ACC_ID") ENABLE;
  ALTER TABLE "ATEAM"."FRIEND_WAIT" ADD CONSTRAINT "FRIEND_WAIT_USER_FK" FOREIGN KEY ("USERID")
	  REFERENCES "ATEAM"."MEM" ("MEM_ACC_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FRIEND
--------------------------------------------------------

  ALTER TABLE "ATEAM"."FRIEND" ADD CONSTRAINT "FRIEND_FK" FOREIGN KEY ("FRIENDID")
	  REFERENCES "ATEAM"."MEM" ("MEM_ACC_ID") ENABLE;
  ALTER TABLE "ATEAM"."FRIEND" ADD CONSTRAINT "FRIEND_USER_FK" FOREIGN KEY ("USERID")
	  REFERENCES "ATEAM"."MEM" ("MEM_ACC_ID") ENABLE;
